### PR TITLE
Issue 208

### PR DESCRIPTION
**Pull request by bella-tassone**

### CODE REVIEW

**Review by chunyuema — COMMENTED** [review]
This "UPDATE CACHE" greeting does not seem right. If you look at the background.js, we have not set up any listeners to respond to "UPDATE CACHE" @bella-tassone

**Comment by chunyuema** [comment]
image

Here are all the listeners we have. I think this is rather an implementation issue from before instead of from this task. We can to fix it in this issue though.

**Comment by SebastianZimmeck** [comment]
> We can to fix it in this issue though.

Yes, let's do that! Did you already start a fix, @chunyuema or is that better to address for you, @bella-tassone?

**Comment by SebastianZimmeck** [comment]
Let's have this fixed by Monday night please.

**Comment by chunyuema** [comment]
I believe that this is fixed. Merging now.

**Pull request merged**
